### ISSUE TITLE
win mode missing translate

### ISSUE THREAD

**Issue by Racpy** [AaronMcKenney/ttt2-role_impo#3]
The current default setting is "Imposter's team wins", but this setting actually means everyone loses, and the missing translation is the correct "Imposter's team wins"
![image](https://github.com/AaronMcKenney/ttt2-role_impo/assets/59442552/49e29064-d202-44ce-8e58-a46fa9232208)

**Comment by AaronMcKenney** [comment]
Thanks for the catch.
